### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'substr')

### ISSUE THREAD

**Issue by Arborerivus** [SvenWerlen/moulinette-sounds#10]
I'm on the Forge, I can't get moulinette-sounds to list my custom sounds folder, in the help menu it recognizes the folders though. 
Not a coder, so I hope the information is sufficient. I get this error everytime I try to scan the sounds folder.

![image](https://user-images.githubusercontent.com/96127307/199271232-77093a0e-00f3-48b4-b031-e0ed079036af.png)

**Comment by SvenWerlen** [comment]
_Sorry for this late answer._ 
This issue should have been fixed in more recent versions. 
Feel free to reopen the issue if it's not the case.
