### ISSUE TITLE
Better short texts for Soundboard

### ISSUE THREAD

**Issue by LinkDragmire** [SvenWerlen/moulinette-sounds#12]
I'm using the soundboard for some sessions now. I'm using different sound for similar events, like different animal noises. Using Icons is kinda difficult for this one. But using the short text on the soundboard is difficult too, because there are only three letters showing (four, when hovering). It would be very useful to have the option to size down the text and use more than one text line.

**Comment by SvenWerlen** [comment]
If you use the new soundboard, you can configure the size of the box (1 to 3)
![image](https://github.com/SvenWerlen/moulinette-sounds/assets/938060/a683a047-3237-4f12-87d4-b55622fbd2a5)

See announcement : https://www.patreon.com/posts/soundboard-for-87628048
