### ISSUE TITLE
Option to Load all sounds with Repeat ON

### ISSUE THREAD

**Issue by brunocalado** [SvenWerlen/moulinette-sounds#3]
Hi.

Can you add an option to set all sounds with repeat on?

Thank you for the great job

![image](https://user-images.githubusercontent.com/4999783/119868260-33304b00-bef5-11eb-866b-403894aadfe2.png)

**Comment by SvenWerlen** [comment]
This is now implemented in `v-2.8.0`. 
![Screenshot_20210727_194113](https://user-images.githubusercontent.com/938060/127241261-0b2d9035-33e6-42df-9024-97b4a7e73ed5.png)
