### ISSUE TITLE
[Feature Suggestion] Allow Drag and Drop from Sound Search to Playlist

### ISSUE THREAD

**Issue by akrigline** [SvenWerlen/moulinette-sounds#5]
Similar to the way [Playlist Enhancer](https://github.com/Mallander/playlist-enhancer) allows sounds to be dragged from one playlist to another, I would like to be able to drag sounds from the search directly into a playlist of my choice.

![moulinette-sounds-demo](https://user-images.githubusercontent.com/7644614/125886256-ef2624a2-c689-428b-9d72-8478d2850bd9.gif)

**Comment by SvenWerlen** [comment]
Thank you for you suggestion. This is now supported by `moulinette-sounds` (version 2.7.0)
