### ISSUE TITLE
Special Char Can Make Music Don't work

### ISSUE THREAD

**Issue by brunocalado** [SvenWerlen/moulinette-sounds#6]
Hi

I have a music pack with # in the name. This makes moulinette don't be able to play them.

![image](https://user-images.githubusercontent.com/4999783/127718806-a152e34d-9f90-44b5-b8e7-73eada1037c4.png)

Thank you.

**Comment by SvenWerlen** [comment]
Fixed in `3.3.0+` (moulinette-sounds). Release expected to be public beginning of February.
