### ISSUE TITLE
2.11.6 fails when sound menu selected

### ISSUE THREAD

**Issue by brother-oak** [SvenWerlen/moulinette-sounds#7]
2.11.4 worked fine with my custom sounds in the sounds directory.

I recently updated to 2.11.6 and now when I select the moulinette icon, then the sounds icon (the note), An "Indexing" bar is briefly displayed, no popup window is displayed, and the following error is displayed in the console:

![image](https://user-images.githubusercontent.com/66773832/144334041-cdef5128-1af9-4b80-bb40-e96f68af6b1d.png)

```

MoulinetteCache | Retrieving https://assets.moulinette.cloud/assets/jc4cncfvmpbq5nm3msxs1e50ra from cache
moulinette-cache.js:26 MoulinetteCache | Retrieving https://assets.moulinette.cloud/byoa/assets/jc4cncfvmpbq5nm3msxs1e50ra from cache
moulinette-file-util.js:438 Moulinette FileUtil |  moulinette/sounds/custom/index.json {target: "moulinette/sounds/custom", private: false, gridSize: null, dirs: Array(2), privateDirs: Array(0), …}
foundry.js:2013 TypeError: Cannot read property 'find' of undefined
[Detected 2 packages: moulinette-sounds, moulinette-core]
    at MoulinetteSounds.getPackList (moulinette-sounds.js:38)
    at async MoulinetteForge.getData (moulinette-forge.js:74)
    at async MoulinetteForge._render (foundry.js:2049)
    at async MoulinetteForge._render (foundry.js:2736)

```

Images and icons etc all work fine (before this error is produced by selecting the note icon)

Note that I am not a patron and just index my local sounds. I tried to delete the index.json file (in case that was causing the problem) but it had no effect.

**Comment by SvenWerlen** [comment]
Fixed in `v-2.11.7`. Thanks for reporting this!
