### ISSUE TITLE
Unable to play audio files indexed from The Forge (User Data or The Bazaar).

### ISSUE THREAD

**Issue by T-Whiz** [SvenWerlen/moulinette-sounds#9]
**Description:**
Audio files indexed by Moulinette Sounds in Forge aren't played as expected in Moulinette Sounds or playlists when the files are in either The Forge's 'User Data' or 'The Bazaar' locations.

Foundry Version: 10.288
Game System: dnd5e, 2.0.3
Hosting: The Forge
Active Modules: Moulinette Core 10.1.1, Moulinette Sounds 10.1.0, The Forge 1.10
OS: Windows 11
Browser: Microsoft Edge Version 106.0.1370.52 (Official build) (64-bit)

**Steps to recreate:**
Prerequisites: The Forge, at least one music/audio module installed (for example "Adventure Music").
1. After loading into the world, launch Moulinette Sounds (from either the Moulinette toolbar or Ambient Sound Controls toolbar).
2. Select Configure Sources.
3. Select Pick folder and navigate to the following: The Bazaar > Modules > adventuremusic
4. Select the Select Directory button.
5. Enter values in the Creator and Pack fields, then select Add source.
6. Close the Sources window and select the Index sounds button in Moulinette Sounds.
7. After indexing is complete, select the Pack from the drop-down list.
8. Attempt to play a track either using Moulinette Sounds buttons or by dragging and dropping into a playlist.

**Expected:**
The sound file can be played through either the Moulinette Sounds buttons ("Play Sound / Sound Stop", "Listen to sound or music (without playing it in Foundry)") or through the Foundry playlist interface after dragging a sound from Moulinette into a playlist.

**Actual:**
The sound isn't played. A 404 error message and a "Failed to load audio node" error message are displayed in the console log (see attached).

Additional notes: Once added to a playlist, a track's Audio Source field can be manually updated from "https%3A//" to "https://" to allow the track to play from the playlist (but remains unplayable from within Moulinette).

Attached log file and screen shots.
[log-file.log](https://github.com/SvenWerlen/moulinette-sounds/files/9862191/log-file.log)
[screen-shots.pdf](https://github.com/SvenWerlen/moulinette-sounds/files/9862192/screen-shots.pdf)

**Comment by SvenWerlen** [comment]
This is an amazing bug report. Thank you for all the details!
I've been able to reproduce it. I fixed it in `v-10.1.1`. 
Unfortunately, I was not able to make the sound duration work properly on The Forge.

**Comment by T-Whiz** [comment]
Thanks very much! The indexing is working as expected now. On a related note, are the path details expected to appear in the track names in the playlist when adding via Moulinette? I wasn’t sure whether this is an expected limitation due to using a hosting service.

**Comment by SvenWerlen** [comment]
Thank you for confirming it. 
You're right, the track name is pretty ugly for this use case and I need to improve it.
I'll put it on my TODO list
